#!/usr/bin/env python3
"""Gera data/result-image-dims.ts com width/height reais de cada imagem
em public/images/results/. Roda em build/CI sempre que imagens mudarem."""
from PIL import Image
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIR = os.path.join(REPO, "public/images/results")
OUT = os.path.join(REPO, "data/result-image-dims.ts")

dims = {}
for fname in sorted(os.listdir(DIR)):
    if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
        continue
    img = Image.open(os.path.join(DIR, fname))
    dims[f"/images/results/{fname}"] = (img.size[0], img.size[1])

with open(OUT, "w") as f:
    f.write("// AUTO-GENERATED by scripts/gen-image-dims.py — do not edit by hand.\n")
    f.write(
        "export const imageDims: Record<string, { width: number; height: number }> = {\n"
    )
    for path, (w, h) in dims.items():
        f.write(f'  "{path}": {{ width: {w}, height: {h} }},\n')
    f.write("};\n")

print(f"Gerado {OUT} com {len(dims)} imagens")
